version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.9
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.1

jobs:
  reversing-labs:
    steps:
      - checkout
  
      - run: dotnet --version


      - run: 
          name: build okta-hosted-login to scan
          command: dotnet build ./okta-hosted-login/okta-aspnet-mvc-example.sln

      - run: 
          name: build primary-auth to scan
          command: dotnet build ./primary-auth/okta-aspnet-mvc-example.sln 

      - run: 
          name: build resource-server to scan
          command: dotnet build ./resource-server/okta-aspnet-webapi-example.sln

      - run: 
          name: build self-hosted to scan
          command: dotnet build ./self-hosted-login/okta-aspnet-mvc-example.sln
      
      - run: 
          name: build social-login to scan
          command: dotnet build ./social-login/okta-aspnet-mvc-example.sln


      // Necessary to Install rl wrapper   
      - run:
          name: Install Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            sudo pip install --upgrade pip
  
      // Download the scanner from Okta Security
      - run:
          name: Download Reverse Labs Scanner
          command: |
            curl https://dso-resources.oktasecurity.com/scanner \
              -H "x-api-key: $RESOURCE_TOKEN" \
              --output rl_wrapper-0.0.2+35ababa-py3-none-any.whl
      // Install the wrapper that was downloaded
      - run:
          name: Install RL Wrapper
          command: |
            pip install ./rl_wrapper-0.0.2+35ababa-py3-none-any.whl
  
      // Setup the AWS profile
      - aws-cli/setup:
          profile_name: default
          role_arn: $AWS_ARN
          region: us-east-1
  
      // Get the credentials and save to env
      - run: >-
          eval "$(aws configure export-credentials --profile default --format env)" 2> /dev/null
  
      // Run the wrapper, do not change anything here
      - run:
          name: Run Reversing Labs Wrapper Scanner
          command: |
            rl-wrapper \
              --artifact ${CIRCLE_WORKING_DIRECTORY/#\~/$HOME} \
              --name $CIRCLE_PROJECT_REPONAME\
              --version $CIRCLE_SHA1\
              --repository $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --commit $CIRCLE_SHA1 \
              --build-env "circleci" \
              --suppress_output


workflows:
  "Malware Scanner":
    jobs:
      - reversing-labs:
          context:
            - okta-dcp 
  # See OKTA-624620
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          context:
            - static-analysis
